### ISSUE TITLE
Remove old branches?

### ISSUE THREAD

**Issue by mvitz** [innoq/statuses#112]
Maybe some of the branches can be deleted?

**Comment by aheusingfeld** [comment]
:+1: 

- `fixed-width-counter` by @fnd [has already been applied to `master`](https://github.com/innoq/statuses/compare/fixed-width-counter) -> remove
- `compojure` seems to be a rather old one by @stilkov, I'm not sure if we still need it
- `revert-65-master` is obsolete: It wanted to revert changes of #65 but the bugs were fixed in #67 and #68 -> remove
- `top-app-menu` by @stilkov [has already been applied to `master`](https://github.com/innoq/statuses/compare/top-app-menu) -> remove

**Comment by stilkov** [comment]
Removed “my” branches

**Comment by FND** [comment]
all done
